version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: preppy
      MONGO_INITDB_ROOT_PASSWORD: preppy-password
    ports:
      - "27017:27017"
